Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.memory = 1024
    v.cpus = 2
  end
 
  config.vm.define "nfss" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "nfss"
  end
 
  config.vm.define "nfsc" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "net1"
    nfsc.vm.hostname = "nfsc"
  end
 
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.ssh/vagrant', '~/.vagrant.d/insecure_private_key']
 
  config.vm.provision :shell, privileged: false do |s|
   ssh_pub_key = File.readlines("#{Dir.home}/.ssh/vagrant.pub").first.strip
   s.inline = <<-SHELL
     echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
     sudo bash -c "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
   SHELL
  end
 
  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ping_playbook.yaml"
     ansible.groups = {
         "NFS_server" => ["nfss"],
         "NFS_client" => ["nfsc"],
         "NFS_hosts:children" => ["NFS_server", "NFS_client"]
     }
  end
 
 end 